### ISSUE TITLE
Wrong charset, conversion from `GBK' to `UTF-8//IGNORE' is not allowed in

### ISSUE THREAD

**Issue by xxfaxy** [aliyun/aliyun-oss-php-sdk#101]
<br />
<b>Notice</b>:  iconv(): Wrong charset, conversion from `GBK' to `UTF-8//IGNORE' is not allowed in <b>/app/vendor/aliyuncs/oss-sdk-php/src/OSS/OssClient.php</b> on line <b>2301</b><br />

**Comment by suconghou** [comment]
use 
```
 OssUtil::checkChar($options[self::OSS_OBJECT], false)
```
it works fine.

**Comment by xiaozhuai** [comment]
alpine? Maybe is the problem with libiconv, you need to install gnu-libiconv, for example Dockerfile
```Dockerfile
RUN apk --no-cache --allow-untrusted --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ add gnu-libiconv
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php
```

**Comment by ahsar** [comment]
> alpine? Maybe is the problem with libiconv, you need to install gnu-libiconv, for example Dockerfile
> 
> ```dockerfile
> RUN apk --no-cache --allow-untrusted --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ add gnu-libiconv
> ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php
> ```

it works, thanks

**Comment by tekintian** [comment]
if (PHP_VERSION_ID > 70100) {
					//高版本的 PHP 不支持 //IGNORE
					$options[self::OSS_OBJECT] = iconv('GBK', "UTF-8", $options[self::OSS_OBJECT]);
				} else {
					$options[self::OSS_OBJECT] = iconv('GBK', "UTF-8//IGNORE", $options[self::OSS_OBJECT]);
				}

**Comment by soniolabs** [comment]
安装 apk add gnu-libiconv 会移除 zlib.so 的扩展？
执行 `RUN apk --no-cache --allow-untrusted --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ add gnu-libiconv` 之前，zlib 扩展是有的，为啥安装之后就没有了呢，因为 zlib 的扩展，很多其他库都会依赖它，求解为何会移除它呢

**Comment by xiaozhuai** [comment]
@soniolabs 我这里并不会 如果你是docker alpine环境 参考 [https://github.com/xiaozhuai/docker-php-fpm-alpine](https://github.com/xiaozhuai/docker-php-fpm-alpine)

**Comment by soniolabs** [comment]
> @soniolabs 我这里并不会 如果你是docker alpine环境 参考 https://github.com/xiaozhuai/docker-php-fpm-alpine

是的，我的是 docker alpine 环境。我是用的 php 的 hyperf 框架，我是dockerfile 一行一行代码执行然后看效果的，确实会把 zlib 移除。通过 apk add php7-zlib 没有效果。执行前我先把 zlib.so 及 zlib.ini文件备份了，执行后我再移到原来位置，目前可以用了，感谢。

[hyperf/hyperf-docker: 🐳The docker image offered by Hyperf.](https://github.com/hyperf/hyperf-docker)

**Comment by limingxinleo** [comment]
@wu2kong 用最新版本

**Comment by limingxinleo** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/issues/12328

**Comment by huiguangjun** [comment]
增加 checkObjectEndcoding 配置选项，默认关闭。
https://github.com/aliyun/aliyun-oss-php-sdk/commit/16b47c626493bbd503402685b65fb5812583d2b5

**Comment by xiaozhuai** [comment]
Use the following trick to work around latest alpine.

```Dockerfile
RUN apk add --no-cache --repository https://dl-cdn.alpinelinux.org/alpine/v3.12/community/ --allow-untrusted gnu-libiconv=1.15-r2
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php
```
