### ISSUE TITLE
会出支持Flysystem的版本吗？

### ISSUE THREAD

**Issue by wyzhcn** [aliyun/aliyun-oss-php-sdk#11]
见http://flysystem.thephpleague.com/

标准化的SDK更方便系统接入

**Comment by rockuw** [comment]
我们会安排开发，近期提供，感谢支持。

**Comment by apollopy** [comment]
https://packagist.org/packages/apollopy/flysystem-aliyun-oss

**Comment by rockuw** [comment]
@apollopy 

:+1:

**Comment by darkyoung** [comment]
@apollopy 
:thumbsup:

**Comment by poem** [comment]
@apollopy
 :thumbsup:

**Comment by medz** [comment]
@darkyoung https://github.com/medz/oss-stream-wrapper
写了一个流协议，支持自定义注册。
应该才是你需要的东西吧？
```php
file_put_contents('oss://demo/test.txt', 'This is a test content.');
```
直接这样操作文件，或者在symfony/finder包中的使用方法：
```php
use Symfony\Component\Finder\Finder;

$finder = new Finder();

$path = 'oss://demo'; //拟定一个已经存在的目录，如果不存在也没关系，流协议中已经支持了目录存在与否的判断，是本地文件一样，没有任何区别。
$finder->files()->in($path);

foreach ($finder as $file) {
  var_dump($file); // Symfony\Component\Finder\SplFileInfo
}
```
我的理解是你需要这个～因为我目前在开发的项目，需要，所以自己写了一个。

**Comment by medz** [comment]
@rockuw 你们是要开发这个？

**Comment by medz** [comment]
@darkyoung 刚认真看了些你说的这个，我已经确定我写的这个自定义流协议就是你要的东西。

**Comment by Master-Xia** [comment]
@apollopy已不再随官方sdk更新，Flysystem版本最好官方维护一下，官方打算维护吗？

**Comment by apollopy** [comment]
@Master-Xia 我更新了 composer.json 的支持，测试用例跑下来是没问题，你可以升升看。

**Comment by baiyubin** [comment]
非常感谢大家的支持，OSS已经支持flysystem， 详见https://github.com/aliyun/aliyun-oss-php-sdk-flysystem。
