### ISSUE TITLE
OSS\Core\OssException' with message 'RequestCoreException: cURL resource: Resource id #12; cURL error: Empty reply from server

### ISSUE THREAD

**Issue by dmskys** [aliyun/aliyun-oss-php-sdk#110]
OSS\Core\OssException' with message 'RequestCoreException: cURL resource: Resource id #12; cURL error: Empty reply from server
是怎么回事
经常出现这个错误！

**Comment by cfeeling** [comment]
我也遇到这个问题了，而且是服务器大量这样的问题，相同的配置，在更新以前没有遇到。

**Comment by xiaozhuai** [comment]
这个问题解决了吗

**Comment by cfeeling** [comment]
我目前是将 OSS 挂载到服务器的其他地方，然后用软链接将挂载目录下的子目录映射到使用到的地方。

**Comment by xiaozhuai** [comment]
ossfs吗? 我是用这个会有比较严重的性能问题. 我后来发现是Expect: 100-continue的问题, 见这个pr. 你可以试试看能不能解决.
https://github.com/aliyun/aliyun-oss-php-sdk/pull/115

**Comment by huiguangjun** [comment]
已合入到master分支
