### ISSUE TITLE
bug：time() 破坏了 代码可测性，test 报错

### ISSUE THREAD

**Issue by sinkcup** [aliyun/aliyun-oss-php-sdk#113]
问题：代码里使用了 time()，导致 test 无法 mock，所以报错。
解决办法：代码里使用 Carbon，test里使用 Carbon::setTestNow(now());

https://github.com/aliyun/aliyun-oss-php-sdk/blob/339a4021da5e763eaa967bd7f67357b7061a3962/src/OSS/OssClient.php#L1867

![2019-04-18 10-11-30屏幕截图](https://user-images.githubusercontent.com/4971414/56332643-bc77de00-61c3-11e9-8ab1-2416c54fbde3.png)
![2019-04-18 10-18-17 的屏幕截图](https://user-images.githubusercontent.com/4971414/56332633-b4b83980-61c3-11e9-97ff-1af37ff73961.png)

**Comment by byan** [comment]
Carbon 太重了，引入 https://github.com/lcobucci/clock 即可。

**Comment by huiguangjun** [comment]
signUrl 和 SignRtmpUrl 这两个 接口  会提供另外一个接口， 参数 timeout 修改为 expiration，
即传入的参数为 unix epoch， 可以根据需求设置不同的过期时间。
