### ISSUE TITLE
[Bug] Cannot be named '0' when creating a directory

### ISSUE THREAD

**Issue by kaysonwu** [aliyun/aliyun-oss-php-sdk#128]
Cannot be named with '0' when creating directory due to judgment using [empty](https://github.com/aliyun/aliyun-oss-php-sdk/blob/master/src/OSS/Core/OssUtil.php#L223) function

**Example**
```
$client->createObjectDir('aliyun', '0');
```

**Comment by huiguangjun** [comment]
fix in 2.4.0
