### ISSUE TITLE
uploadfile没法自定义content-type

### ISSUE THREAD

**Issue by ccqgithub** [aliyun/aliyun-oss-php-sdk#13]
public function uploadFile($bucket, $object, $file, $options = NULL)
    {
        $this->precheckCommon($bucket, $object, $options);
        OssUtil::throwOssExceptionWithMessageIfEmpty($file, "file path is invalid");
        $file = OssUtil::encodePath($file);
        if (!file_exists($file)) {
            throw new OssException($file . " file does not exist");
        }
        $options[self::OSS_FILE_UPLOAD] = $file;
        $file_size = filesize($options[self::OSS_FILE_UPLOAD]);
        $is_check_md5 = $this->isCheckMD5($options);
        if ($is_check_md5) {
            $content_md5 = base64_encode(md5_file($options[self::OSS_FILE_UPLOAD], true));
            $options[self::OSS_CONTENT_MD5] = $content_md5;
        }
        $content_type = $this->getMimeType($file);
        $options[self::OSS_METHOD] = self::OSS_HTTP_PUT;
        $options[self::OSS_BUCKET] = $bucket;
        $options[self::OSS_OBJECT] = $object;
        $options[self::OSS_CONTENT_TYPE] = $content_type;
        $options[self::OSS_CONTENT_LENGTH] = $file_size;
        $response = $this->auth($options);
        $result = new PutSetDeleteResult($response);
        return $result->getData();
        }

content-type是根据$file取的，但是上传文件的时候很多时候没有后缀名的，所以这里取到的并不正确，是不是应该如果options里定义了content-type就不要覆盖。

**Comment by rockuw** [comment]
最新版本已经fix了这个问题，你检查一下OssClient.php中的version。

**Comment by ccqgithub** [comment]
好像是，我更新下~~3q
