### ISSUE TITLE
自定义域名后开启 CDN 加速 bug

### ISSUE THREAD

**Issue by iiDestiny** [aliyun/aliyun-oss-php-sdk#137]
## 问题
开启自定义域名之后此时上传没有问题，然后再开 cdn 加速上传就有问题，直接报错

endpoint: http://os.xxxx.com
bucket: xxx
isCname: true

```
client->putObject($this->bucket, $path, $contents, $options);
```

## 报错信息

```
{
    "status": "403",
    "request-id": "5E7F892260097C32372045DE",
    "code": "",
    "message": "",
    "body": ""
}
```

**Comment by iiDestiny** [comment]
@yami @JacksonTian @rockuw @hefei1986 

抱歉打扰，这个问题之前出现过吗？还是使用的问题。

**Comment by iiDestiny** [comment]
问题可以定位到：doesObjectExist 这个方法。如果是 cdn 加速域名返回

![image](https://user-images.githubusercontent.com/17637481/77852173-c1387500-720f-11ea-8b8a-cbd7019c9a01.png)

**Comment by Westeteren** [comment]
开启cname后需要将endpoint填写为cname域名

**Comment by JacksonTian** [comment]
这个需要提工单咨询一下。
