### ISSUE TITLE
大量TCP连接处于CLOSE_WAIT状态

### ISSUE THREAD

**Issue by luojixinhao** [aliyun/aliyun-oss-php-sdk#14]
大量TCP连接处于CLOSE_WAIT状态

**Comment by rockuw** [comment]
你用的php版本是什么？

**Comment by luojixinhao** [comment]
PHP 7.0.2

**Comment by rockuw** [comment]
你好，php 7下SDK目前是有问题的，请使用php >= 5.3的更低版本。

**Comment by rockuw** [comment]
参考 #12

**Comment by lvyalin** [comment]
php7中curl模块 关闭fd的逻辑和原来的不一样，处于全局中的fd，close不了

在oss/http/requestcore.php中672添加
$this->request_headers["Connection"] = "close";

可以临时解决

**Comment by zhuzhsh** [comment]
需要去掉RequestCore对CURL_Handler的依赖，不要相互引用！

**Comment by NextSeason** [comment]
这些问题有修复计划么？还是已经修复了？

**Comment by baiyubin** [comment]
有修复计划的，修复完成后会在这个Issue上说明。

**Comment by iwege** [comment]
这个问题是否已经修复了？

**Comment by baiyubin** [comment]
您好，已经在V2.2.2中修复。非常感谢您的反馈。
