### ISSUE TITLE
MissingContentLength: You must provide the Content-Length HTTP header

### ISSUE THREAD

**Issue by jyiL** [aliyun/aliyun-oss-php-sdk#149]
$ossClient->uploadFile($bucket, $object, $filePath);
上传文件返回MissingContentLength
打印了header的确没有MissingContentLength

**Comment by jyiL** [comment]
docker环境问题,close

**Comment by OverNaive** [comment]
同样遇到 MissingContentLength 报错，请求楼上是如何解决的？

**Comment by OverNaive** [comment]
同样遇到 MissingContentLength 报错，请求楼上是如何解决的？

@jyiL
