### ISSUE TITLE
这个方法似乎没用，中间转化了编码，最后还是会赋值 tmp_object

### ISSUE THREAD

**Issue by limingxinleo** [aliyun/aliyun-oss-php-sdk#151]
![image](https://user-images.githubusercontent.com/16648551/99474476-9f028b80-2987-11eb-9129-f38770ab2518.png)

**Comment by huiguangjun** [comment]
已修复 https://github.com/aliyun/aliyun-oss-php-sdk/commit/16b47c626493bbd503402685b65fb5812583d2b5
