### ISSUE TITLE
PHP8 因为 is_resource 的返回值改变，抛出了异常

### ISSUE THREAD

**Issue by jetiben** [aliyun/aliyun-oss-php-sdk#154]
PHP8 不能使用 is_resource 来判断 $curl_handle，希望能火速兼容。

**Comment by zmou** [comment]
官方尽快修复这个问题啊，我们有好几个项目用的是PHP8，现在被迫降低到php7.3 了，阿里云这响应速度慢如蜗牛啊

**Comment by JimmyKmi** [comment]
同样遇到PHP8兼容问题，请官方尽快修复啊，已经在聆听提交了建议
实在不行就要用~~腾讯...~~

**Comment by Reshared** [comment]
我的天，都这么久了还没解决么？

**Comment by rust17** [comment]
这速度，已经自行修改源码改用自己的镜像了。。。

**Comment by clerkzhang** [comment]
我丢， 这是想让大家用别的原因， 一直异常

**Comment by daqiaowijiu** [comment]
我丢，还没更

**Comment by imlida** [comment]
阿里云啊阿里云，用户的声音听不见吗？这么久都不修复

**Comment by soonio** [comment]
去阿里云控制台里面投诉啊兄弟们，真的是太慢太坑了

**Comment by orginly** [comment]
那么久了 太慢了啊

**Comment by shijie1991** [comment]
前来膜拜 ORZ

**Comment by pocuno** [comment]
严重考虑弃用了

**Comment by Marchccc** [comment]
搞快点
