### ISSUE TITLE
PHP8以上的情况下is_resorce函数执行不正常

### ISSUE THREAD

**Issue by LittleMonsterAK** [aliyun/aliyun-oss-php-sdk#171]
vendor/aliyuncs/oss-sdk-php/src/OSS/Http/RequestCore.php  792

php8中逐步将resource类型替换成class object， curl初始化后生成的不再是资源类型，所以这里is_resource会失败。
改成  $curl_handle !==  false

**Comment by huiguangjun** [comment]
近期会发版本支持php8

**Comment by huiguangjun** [comment]
已提交
