### ISSUE TITLE
上传文件设置Content-Disposition失败

### ISSUE THREAD

**Issue by JackyChan** [aliyun/aliyun-oss-php-sdk#19]
在上传文件时，指定了Content-Disposition参数，但是文件上传成功，但是Content-Disposition却没有设置成功。

**Comment by rockuw** [comment]
需要指定options:

```php
$options = array(
      OssClient::OSS_HEADERS => array(
          'Content-Disposition' => 'attachment; filename="xxxxxx"'
      )
);
```

**Comment by JackyChan** [comment]
谢谢，成功了，我以为是这样写：
$options = array(
          'Content-Disposition' => 'attachment; filename="xxxxxx"'
);

**Comment by rockuw** [comment]
这个地方是有些误导，我们后续会改善一下。
