### ISSUE TITLE
API调用，如何获取ResponseCore或者Result对象

### ISSUE THREAD

**Issue by edwardaa** [aliyun/aliyun-oss-php-sdk#2]
如果调用`OssClient::listObjects()`出现异常则直接抛`OssException`，除此之外无法得知HTTP status code和异常信息：比如，`InvalidAccessKeyId`, `SignatureDoesNotMatch`.

而之前的老版本是可以的，因为它的接口调用直接返回`ResponseCore`对象.

**Comment by edwardaa** [comment]
我看到OssException::message里包含了`Code`, `Message`, `Reason`等字段，能否增加这些字段相应的OssException成员变量，而OssException::message换成普通信息，这样更好了。

**Comment by rockuw** [comment]
谢谢你的建议，我们会在下一个小版本中解决这个问题。
