### ISSUE TITLE
上传文件时，不能设置header, OSS_CONTENT_DISPOSTION

### ISSUE THREAD

**Issue by liaoxw** [aliyun/aliyun-oss-php-sdk#20]
上传文件时，不能设置header, OSS_CONTENT_DISPOSTION,导制不能下载是按上传文件时不能按 OSS_CONTENT_DISPOSTION描述的文件名下载

OssClient.php
private function generateHeaders($options, $hostname)

$headers = array(
            self::OSS_CONTENT_MD5 => '',
            self::OSS_CONTENT_TYPE => isset($options[self::OSS_CONTENT_TYPE]) ? $options[self::OSS_CONTENT_TYPE] : self::DEFAULT_CONTENT_TYPE,
            self::OSS_DATE => isset($options[self::OSS_DATE]) ? $options[self::OSS_DATE] : gmdate('D, d M Y H:i:s \G\M\T'),
            self::OSS_HOST => $hostname,
            self::OSS_CONTENT_DISPOSTION => isset($options[self::OSS_CONTENT_DISPOSTION]) ? $options[self::OSS_CONTENT_DISPOSTION] : '',
        );
＃1917
加上这个
self::OSS_CONTENT_DISPOSTION => isset($options[self::OSS_CONTENT_DISPOSTION]) ? $options[self::OSS_CONTENT_DISPOSTION] : '',

**Comment by rockuw** [comment]
参考 #19
