### ISSUE TITLE
how to use set_enable_domain_style?

### ISSUE THREAD

**Issue by johnsonbb** [aliyun/aliyun-oss-php-sdk#22]
i could not find any function to create domain name alias with oss endpoint.

**Comment by rockuw** [comment]
Version >= 2.0 uses endpoint like this: `my-bucket.oss-cn-hangzhou.aliyuncs.com` by default.

**Comment by johnsonbb** [comment]
is it possible to bind a domain name (example.com) to oss?

**Comment by rockuw** [comment]
Refer to https://help.aliyun.com/document_detail/oss/sdk/php-sdk/init.html

"使用自定义域名(CNAME)新建OssClient"

**Comment by johnsonbb** [comment]
thanks alot!!
i found the function addBucketCname is what i need ;)
