### ISSUE TITLE
centos服务器，php上传碰到问题： cURL resource: Resource id #58; cURL error: select/poll returned error (55)

### ISSUE THREAD

**Issue by znau** [aliyun/aliyun-oss-php-sdk#25]
之前都是ok 的 ，最近突然发生这个问题，影响了我所有的上传。

RequestCoreException: cURL resource: Resource id #58; cURL error: select/poll returned error (55)
错误位置
FILE: /usr/share/nginx/html/ThinkPHP/Library/Vendor/Alioss/src/OSS/OssClient.php 　LINE: 1641
TRACE
#0 /usr/share/nginx/html/ThinkPHP/Library/Vendor/Alioss/src/OSS/OssClient.php(782): OSS\OssClient->auth(Array)
#1 /usr/share/nginx/html/Application/Common/Common/function.php(1088): 

*********************

**Comment by rockuw** [comment]
curl error 55是网络错误，你可以通过curl endpoint看一下网络是否是通的。

**Comment by znau** [comment]
果然是网络问题  我用ossprobe 工具找到了 谢谢！！！！
