### ISSUE TITLE
signUrl方法 options 指定Content-Type后提示签名错误

### ISSUE THREAD

**Issue by guxiangming** [aliyun/aliyun-oss-php-sdk#252]
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>

**Comment by huiguangjun** [comment]
已更新签名代码 https://github.com/aliyun/aliyun-oss-php-sdk/commit/af38fe3f60abe89c9a3cb986d81b0f44e41a7e1f
