### ISSUE TITLE
上传完成以后，PutSetDeleteResult 解析上传结果的逻辑没有实现

### ISSUE THREAD

**Issue by ihipop** [aliyun/aliyun-oss-php-sdk#26]
https://github.com/aliyun/aliyun-oss-php-sdk/blob/master/src/OSS/Result/PutSetDeleteResult.php#L17

响应上可以获取上传后的result的，包括返回的文件的md5的etag头 ,文件网址等。

![image](https://cloud.githubusercontent.com/assets/423077/16605785/b8433ca6-4364-11e6-8a34-5b64b878759c.png)

其他SDK都有实现了的 [官方说明](https://help.aliyun.com/document_detail/32030.html#返回值)

[代码出处1](https://github.com/aliyun/aliyun-oss-python-sdk/blob/f72cd78bea7882262e62c96722514eabf1c1569e/oss2/api.py#L294)

 [代码出处2](https://github.com/aliyun/aliyun-oss-python-sdk/blob/4b1456e3dea881e03ec90d9e68bd078d46913cc3/oss2/models.py#L95)

**Comment by rockuw** [comment]
非常合理的需求，我们会在下一个版本中支持。

**Comment by greedying** [comment]
现在仍然没有实现。哎。。。哪怕你们就返回一个true也行啊。这返回个null，害多少人一次次的跟代码。。

**Comment by xiaohuilam** [comment]
操蛋的代码，还阿里云官方。。。坑货

**Comment by baiyubin** [comment]
非常抱歉给您带来了困扰，我们将尽快修复该问题。

**Comment by qiawei** [comment]
这个地方确实坑死我了。。。

**Comment by baiyubin** [comment]
您好，2.2.0版本中已修复。
