### ISSUE TITLE
GetObject支持带response-content-disposition等参数

### ISSUE THREAD

**Issue by shinenuaa** [aliyun/aliyun-oss-php-sdk#27]
GetObject支持带response-content-disposition等参数 ，详见[GetObject](https://help.aliyun.com/document_detail/31980.html?spm=5176.doc31947.6.270.i6toka).

**Comment by baiyubin** [comment]
已经纳入了开发计划。谢谢您的反馈。

**Comment by ljbreak2008** [comment]
您好，aliyun-oss-php-sdk暂时不支持该功能 ,谢谢。
