### ISSUE TITLE
希望增加对异步处理（x-oss-async-process）的支持

### ISSUE THREAD

**Issue by FlyingBlazer** [aliyun/aliyun-oss-php-sdk#271]
OSS中部分操作仅支持[异步处理](https://help.aliyun.com/zh/oss/user-guide/asynchronous-processing)，但phpsdk目前对此没有支持，希望尽快添加

**Comment by huiguangjun** [comment]
已添加 https://github.com/aliyun/aliyun-oss-php-sdk/commit/58265ff343724f304ca2339380e6a0cdb1bcb946
