### ISSUE TITLE
Translating into English

### ISSUE THREAD

**Issue by mosuke5** [aliyun/aliyun-oss-php-sdk#28]
Hi

This sdk document is Chinese.
But we Japanese also use this library.
Will you tranlate it into English?
If I request PR of translating into English, do you merge?

**Comment by rockuw** [comment]
Hi, sorry for the inconvenience. We'll arrange for the translating. 

If you already started the translating, we can collaborate on that. Your contribution is really appreciated.

Thank you.

**Comment by mosuke5** [comment]
Thank you for replying.
I staill haven't started it. If I translate it, I request PR to this repository?

**Comment by rockuw** [comment]
Yes.

**Comment by mosuke5** [comment]
Ok. thank you
