### ISSUE TITLE
php8.1报错.strlen(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by bkkkd** [aliyun/aliyun-oss-php-sdk#289]
php8.1报错.
strlen(): Passing null to parameter #1 ($string) of type string is deprecated
`

        if (strlen($credentials->getSecurityToken()) > 0) {
            $request->add_header("x-oss-security-token", $credentials->getSecurityToken());
        }`

建议修改为
`if (strlen($credentials->getSecurityToken()?:'') > 0) `

**Comment by byan** [comment]
直接 !empty($credentials->getSecurityToken()) 即可

**Comment by bkkkd** [comment]
> 直接 !empty($credentials->getSecurityToken()) 即可，请尽快修复。大部分情况都是通过角色控制权限的。

都可以.尽快修复吧.

**Comment by ShaBaoFa** [comment]
<img width="272" alt="50f03d7ace328929b7d67e799b81fa3" src="https://github.com/aliyun/aliyun-oss-php-sdk/assets/8308381/a6db8df6-aeac-4132-ba25-eee84861dc1e">
<img width="382" alt="2b29aad9fbd66c1596e5803262f0559" src="https://github.com/aliyun/aliyun-oss-php-sdk/assets/8308381/cfa5e298-95a5-48cf-86a0-9eb3f6680478">
只能说写java sdk和php sdk 的代码哲学不太一样。

**Comment by bkkkd** [comment]
@huiguangjun
@yangzong18
有空修复一下?

**Comment by huiguangjun** [comment]
https://github.com/aliyun/aliyun-oss-php-sdk/commit/efca2592105d9425ce32a46215b51a2273ead222
