### ISSUE TITLE
8.0以上PHP版本null值报错

### ISSUE THREAD

**Issue by gigiah** [aliyun/aliyun-oss-php-sdk#290]
src/OSS/SignerV1.php 
18行：strlen($credentials->getSecurityToken()) 如果$credentials->getSecurityToken() = null, strlen会触发报错
27行：parse_str($queryString, $query); $queryString = null, parse_str会报错

**Comment by ShaBaoFa** [comment]
<img width="272" alt="50f03d7ace328929b7d67e799b81fa3" src="https://github.com/aliyun/aliyun-oss-php-sdk/assets/8308381/fec518d5-b971-4733-9b4d-78857307950d">
<img width="382" alt="2b29aad9fbd66c1596e5803262f0559" src="https://github.com/aliyun/aliyun-oss-php-sdk/assets/8308381/2b72e785-c717-426b-b20a-2ccaf9e1eb78">


java里的解决方案就很好，php从2.4开始就一直是这样子写。（印象里）

**Comment by huiguangjun** [comment]
以提交 到 https://github.com/aliyun/aliyun-oss-php-sdk/commit/efca2592105d9425ce32a46215b51a2273ead222
