### ISSUE TITLE
PHP SDK: 分片上传后，Etag, Content-MD5 错误

### ISSUE THREAD

**Issue by mztest** [aliyun/aliyun-oss-php-sdk#32]
分片上传后，Etag, Content-MD5 错误。

文件使用multiuploadFile分片上传，当文件大小超过 OssUtil::OSS_MID_PART_SIZE或者设置分片大小，进行上传， 完成上传后， 使用getObjectMeta, 
etag出现带编号的字符，类似""DBBCA06B72052598E18B038678236B8B-5""， 
Content-MD5值为空不存在。

错误似乎发生：completeMultipartUpload
对象的ETag变成了这个请求中XML加密后生成的ETag。
这里似乎缺少一步，即设置整个文件对象的ETag以及Content-MD5。

https://help.aliyun.com/document_detail/31995.html?spm=5176.doc31947.6.882.HiU2Cu 在这个链接中返回示例中返回也是类似的ETag。

但是如果按照这个逻辑，整个OSS通过分片上传产生的ETag以及Content-MD5都会有问题，那其它用户是如何取得正确的Content-MD5的？

2017年1月3日 18：19 更新
刚才对WEB端JS上传进行测试，如果进行分片上传，该对象的ETag及Content-MD5同样会使用最后一片上传内容的ETag和Content-MD5。

那如果假定所有的Content-MD5不可用，如何使用SDK取得某一个对象的正确的Content-MD5值？

**Comment by mztest** [comment]
到底是不是问题？ 还是我的思考方式有问题，提出的问题根本就不存在，各位到是给句话啊。

**Comment by baiyubin** [comment]
您好，默认情况下multiuploadFile在文件大于OSS_MID_PART_SIZE时候采用分片上传，小于OSS_MID_PART_SIZE采用普通上传。ETag是文件内容的中一个Hash值，不是MD5值，用于标志文件内容的。分片上传由于支持比并发分片上传，整个文件无法支持计算MD5，但是每个分片依然支持MD5作为内容校验。

**Comment by houzhiqiang** [comment]
竟然不支持获取整个文件的md5，难道要用户下载回来自行计算吗？
