### ISSUE TITLE
2.2.1的phar包在5.3.29下引入有问题?

### ISSUE THREAD

**Issue by haijiao1945** [aliyun/aliyun-oss-php-sdk#33]
因为项目用的yii1的版本 所以图方便直接下了个phar来用 在本地php7下测试通过

但是线上环境是5.3.29 一引入文件就爆出两个?? 然后代码执行就断了..请问有人遇到过没有..

**Comment by haijiao1945** [comment]
升级了线上环境为5.5后解决了...本地也换成5.3试了下,也是不能运行,看来就是单纯的不支持5.3

**Comment by RobertYue19900425** [comment]
php5.3也是一直支持phar的，我也刚刚写了个程序在php5.3上验证了下，是可以的。
1.你的具体场景是什么？（当初不能排除我们某些场景没有测到） 
2.具体是报什么错？可以贴出来
3.最好可以先定位代码大概在哪里出错，这样有助于我们两个的高效交流和快速解决问题

**Comment by haijiao1945** [comment]
我在我的一个类的方法里 include phar的文件后代码就停止执行了

显示的是两个问号 像是什么致命错误 PHP本身没有查到错误日志

仅仅在引入文件后就报错,还没到执行具体的方法~
