### ISSUE TITLE
MNS 的SDK有计划托管到github 并放到 composer里吗？

### ISSUE THREAD

**Issue by kids-return** [aliyun/aliyun-oss-php-sdk#37]
类似这个SDK的这种形式

**Comment by 84hero** [comment]
够呛，这些SDK应该不是同一个部门开发的

**Comment by 84hero** [comment]
composer require wushunyi/aliyun-sdk-mns

**Comment by baiyubin** [comment]
您好，多谢您的反馈。我已经将该需求同步给MNS，后继关注[aliyun-mns-php-sdk](https://github.com/aliyun/aliyun-mns-php-sdk)。
