### ISSUE TITLE
调用OssClient->putObject方法，如果$object中含有百分号就会出问题

### ISSUE THREAD

**Issue by klom303** [aliyun/aliyun-oss-php-sdk#40]
调用OssClient->putObject方法，
如果$object中含有百分号就会抛出一个空的异常，内容如下
“: RequestId:”

测试参数
putObject($config, 'test/%.txt', 'test content');

从源码中获取了下response

body:
```
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\r\n
    <html>\r\n
    <head><title>400 Bad Request</title></head>\r\n
    <body bgcolor="white">\r\n
    <h1>400 Bad Request</h1>\r\n
    <p>Your browser sent a request that this server could not understand.<hr/>Powered by AliyunOSS</body>\r\n
    </html>\r\n

```

**Comment by ljbreak2008** [comment]
您好，上传时名称如遇到特殊字符需要先进url转译
example:

$object = '%.txt';

$urlencodeObject = urlencode($object);

$ossClient = new OssClient($accessKeyId, $accessKeySecret, $endpoint,);

$ossClient->putObject($bucket,  $urlencodeObject,  'test content');

**Comment by huiguangjun** [comment]
fix in  https://github.com/aliyun/aliyun-oss-php-sdk/commit/af38fe3f60abe89c9a3cb986d81b0f44e41a7e1f
