### ISSUE TITLE
设置header头不起作用

### ISSUE THREAD

**Issue by apptut** [aliyun/aliyun-oss-php-sdk#45]
使用cliecnt->uploadFile()设置：options 设置：
```
$options = [
            'Expires' => new DateTime("+5 years"), // 获取5年
            'Cache-Control' => 'public, max-age=31536000' // 缓存一年
        ];
```
根本就不起作用，而我使用一个非官方的sdk竟然可以

**Comment by ljbreak2008** [comment]
您好，请使用如下方法设置options，
example:
$options = array(
        OssClient::OSS_HEADERS => array(
            'Expires' => '2010-10-07 08:00:00',
            'Content-Disposition' => 'attachment; filename="xxxxxx"',
    ));
$local_path='test.txt';
$ossClient = new OssClient($accessKeyId, $accessKeySecret, $endpoint);
$ossClient->uploadFile($bucket, $object ,$local_path,$options);

**Comment by baiyubin** [comment]
请参考官网的 [设置文件元信息](https://help.aliyun.com/document_detail/32103.html)。
