### ISSUE TITLE
如何直接将分片上传(即假定当前已分片好),然后对所有分片进行合并.

### ISSUE THREAD

**Issue by amhoho** [aliyun/aliyun-oss-php-sdk#49]
你好,我在sdk开发遇到了一个问题,来请教一下工程师.
 
已实现的传到本地服务器流程:1前端将文件分片=2传至服务器=3最后一片完成

传至OSS:2和3是如何用SDK里的分片上传进行实现,我看文档里都是用**本地的整个文件进行分片然后再每片上传**

但我是已经由前端分片好了,**目标**是将**前端发送的一片片传至OSS**,这样不知道怎么用SDK实现.

**Comment by baiyubin** [comment]
您好，分片方法请参看`OssClient->generateMultiuploadParts`，使用`ossClient->initiateMultipartUpload`初始化分片上传任务，再使用`OssClient->uploadPart`上传分片，上传完成后使用`OssClient->completeMultipartUpload`提交上传分片结果。具体使用方法请参考 [GitHub](https://github.com/aliyun/aliyun-oss-php-sdk/blob/master/tests/OSS/Tests/OssClientMultipartUploadTest.php)。
