### ISSUE TITLE
PHP7.1.0不兼容问题

### ISSUE THREAD

**Issue by liaoyizhe** [aliyun/aliyun-oss-php-sdk#50]
在公司的测试服务器上,php版本是7.1.0。sdk里面代码很多不兼容。
$response = $this->auth($options); 代码里面的依赖报错了，改了几个问题(iconv函数)还是有错误,到后面都没办法调试了.希望官方fix下！

**Comment by lomotony** [comment]
你怎么调用的，我的怎么是好的

**Comment by ljbreak2008** [comment]
我这边PHP7.1版本是好的，并没有出现sdk代码不兼容的问题

**Comment by lxon** [comment]
在Ubuntu 16.4
- PHP 7.0.19

调整了：
- error_reporting(e_all) 
- ini_set('display_errors' 1)

Framework:
- Codeigniter 

use OSS\OSSClient;
use OSS\Core\OSSException;
执行 $ossClient = new OssClient($accessKeyId, $accessKeySecret, $endpoint);

完全没有log或error，一片空白。
检查了/var/log/apache2/error.log也没有相关讯息。

===============

在local mac os的xampp
- PHP 7.1.10

一切正常。

===============

不懂是不是兼容性问题，
还是需要调整php.ini？
若需要调php.ini需要注意哪个选项？
