### ISSUE TITLE
creatbucket时报错了

### ISSUE THREAD

**Issue by gengxiankun** [aliyun/aliyun-oss-php-sdk#52]
The request signature we calculated does not match the signature you provided. Check your key and signing method.

这是什么情况下才会出现啊？我测试了一下不存在的bucket才会报这个错呢。。

**Comment by baiyubin** [comment]
您好，这个是错误是签名错误，解决方法请参看 [https://help.aliyun.com/document_detail/31945.html](https://help.aliyun.com/document_detail/31945.html)  的 `SignatureDoesNotMatch.The request signature we calculated…错误` 章节。
