### ISSUE TITLE
能不能出个简单版的，不用java的模式来写php

### ISSUE THREAD

**Issue by minicase** [aliyun/aliyun-oss-php-sdk#62]
由于php是运行时加载源文件，他的运行机制和其他语音由本质区别，php层面应该尽量轻薄，这么简单个东西，每一次访问都得加载这么一大堆零碎的文件，执行效率和开发效率都很低

**Comment by philwu** [comment]
不管什么语言，OO一定没错。再说现在也没有很复杂，上传和下载，都在10行代码左右就能解决。就算不用OO，估计也是这个长度。

**Comment by minicase** [comment]
没说OO错，就是当下的php还没有JIT，还是常规模式像新浪微博api那样就可以啦，很自然。谁让PHP天生就不适合搞java C# 那样的重度OO。

**Comment by minicase** [comment]
![qq 20171206195036](https://user-images.githubusercontent.com/9739133/33660468-d9e2e0a8-dabe-11e7-8a9a-04f54c61d16e.png)

**Comment by philwu** [comment]
说明你该换编辑器了，推荐VScode或sublime text。

如果非要用这个（这是Zend吗？），就研究一下这个编辑器应该怎样载入external phar library，而不是在这里发牢骚。作者不会因为你的牢骚改变包的结构。这个PHP包并不是阿里OSS服务的一部分，不要在开源社区做伸手党。

觉得不好、不方便、不服气的话，HTTP的标准也都在那里，自己做一个服务于大家嘛，这才是开源社区的精神。

**Comment by minicase** [comment]
你们自己的商业项目啊，让别人给你们做一个开源的，不说了
