### ISSUE TITLE
请问:什么情况下 会出现 RequestId 为空 status 返回 400

### ISSUE THREAD

**Issue by zhongbm** [aliyun/aliyun-oss-php-sdk#88]
![2018-05-17 18 20 32](https://user-images.githubusercontent.com/17777554/40171811-08118af0-59ff-11e8-864e-ca309be11f13.png)
![2018-05-17 18 21 09](https://user-images.githubusercontent.com/17777554/40171840-1b35afa8-59ff-11e8-920f-2f3eb570bbf2.png)

**Comment by yisonli** [comment]
最后是怎么解决的？
